version: "2"
services:
    app:
        image: oneeg/php:7.2-apache
        volumes:
            - $APP_PATH:/app
        ports:
            - $APP_HOST_PORT:80
        env_file:
          - $APP_PATH/.env
